---
- name: Provision the sandbox instance
  hosts: localhost
  vars:
    terminate_instance: true
    name_tag: stv
    region: us-west-1
    keypair: sandbox
    security_group: sandbox-security-group
    instance_type: t2.micro
    ami: ami-XXXXXXX
    vpc_subnet_id: "{{ vpc.vpc.id }}"
    assign_public_ip: yes
    wait: true
    instance_tags:
      Name: Instance Name Goes Here
    root_ebs_size: 16
    zone: us-west-1a
    instance_profile_name:
      key: value
      todo: what is this?
    dns_zone: sandbox.class.stanford.edu
    dns_name: stv
  roles:
    - sandbox
