- name: Deploy Course Discovery
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    serial_count: 1
  serial: "{{ serial_count }}"
  roles:
    - docker
    - nginx
    - role: course_discovery
      nginx_default_sites:
        - course_discovery