---
# TODO: Tag internet_gateway.Name
- name: create a vpc
  local_action:
    profile: "{{ vpc_aws_profile }}"
    module: "ec2_vpc_local"
    resource_tags: "{{ vpc_tags }}"
    cidr_block: "{{ vpc_cidr }}"
    region: "{{ vpc_aws_region }}"
    state: "present"
    internet_gateway: yes
    wait: yes
  register: created_vpc

- name: create public network acl
  ec2_acl:
    profile: "{{ vpc_aws_profile }}"
    name: "{{ vpc_public_acl.name }}"
    vpc_id: "{{ created_vpc.vpc_id }}"
    state: "present"
    region: "{{ vpc_aws_region }}"
    rules: "{{ vpc_public_acl.rules }}"
  register: created_public_acl

- name: create public route table
  ec2_rt:
    profile: "{{ vpc_aws_profile }}"
    vpc_id: "{{ created_vpc.vpc_id }}"
    region: "{{ vpc_aws_region }}"
    state: "present"
    name: "{{ vpc_name }}-public"
    routes: "{{ vpc_public_route_table }}"
  register: created_public_rt

- name: create public subnets
  ec2_subnet:
    profile: "{{ vpc_aws_profile }}"
    vpc_id: "{{ created_vpc.vpc_id }}"
    region: "{{ vpc_aws_region }}"
    state: "present"
    name: "{{ item.name }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    route_table_id: "{{ created_public_rt.id }}"
    network_acl_id: "{{ created_public_acl.id }}"
  with_items: vpc_public_subnets
  register: created_public_subnets


- name: create security group
  ec2_group:
    name: "{{ SECURITY_GROUP_NAME }}"
    description: "{{ SECURITY_GROUP_DESCRIPTION }}"
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ vpc_aws_region }}"
    resource_tags:
      Name: "{{ SECURITY_GROUP_NAME }}"
    rules:
      - proto: tcp
        from_port: "{{ PORT_LMS }}"
        to_port: "{{ PORT_LMS }}"
        cidr_ip: "{{ CIDR_PUBLIC }}"
      - proto: tcp
        from_port: "{{ PORT_CMS }}"
        to_port: "{{ PORT_CMS }}"
        cidr_ip: "{{ CIDR_PUBLIC }}"
      - proto: tcp
        from_port: "{{ PORT_SSH }}"
        to_port: "{{ PORT_SSH }}"
        cidr_ip: "{{ CIDR_PUBLIC }}"

- name: create hosted zone
  route53_zone:
    state: present
    zone: "{{ route53_zone }}"
    comment: "{{ route53_zone_comment }}"
#
# - name: create vpc
#   ec2_vpc:
#     state: present
#     cidr_block: "{{ vpc_cidr }}"
#     region: "{{ vpc_aws_region }}"
#     resource_tags:
#       Name: "{{ NAME_VPC }}"
#     internet_gateway: True
#     subnets:
#       - cidr: "{{ CIDR_SUBNET }}"
#         az: "{{ AVAILABILITY_ZONE }}"
#         resource_tags:
#           Name: "{{ NAME_SUBNET }}"
#         assign_public_ip: True
#         network_acl_id: "{{ network_acl.id }}"
#     route_tables:
#       - subnets:
#           - "{{ CIDR_SUBNET }}"
#         routes:
#           - dest: "{{ CIDR_PUBLIC }}"
#             gw: igw
#   register: vpc
