#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p {{ ansible_jumpbox }}"'
    CLUSTER_NAME: build
    CLUSTER_NUMBER: 1
  when: redeploy | default(False) | bool
- name: "Setup {{ COMMON_HOSTNAME }}"
  hosts:
    - "{{ CLUSTER_NAME }}{{ CLUSTER_NUMBER }}[-1]"
  gather_facts: True
  become: true
  vars:
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p {{ ansible_jumpbox }}"'
    CLUSTER_NAME: build
    CLUSTER_NUMBER: 1
    jenkins_server_name: '_'
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
  roles:
    - deploy_manually
    - role: jenkins_master
- include: ../playbooks/ami.yml
  when: redeploy | default(False) | bool
