#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_INSTANCE_TYPE: 'r4.large'
    CLUSTER_NAME: coursegraph
    CLUSTER_NUMBER: 1
  when: redeploy | default(False) | bool
- name: "Setup {{ COMMON_HOSTNAME }}"
  hosts:
    - "{{ CLUSTER_NAME }}{{ CLUSTER_NUMBER }}[-1]"
  gather_facts: True
  become: true
  vars:
    CLUSTER_NAME: coursegraph
    CLUSTER_NUMBER: 1
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
  roles:
    - neo4j
