#!/usr/bin/env ansible-playbook
---
- include: ../playbooks/cluster.yml
  vars:
    CLUSTER_ASSIGN_PUBLIC_IP: yes
    CLUSTER_NAME: jump
    CLUSTER_NUMBER: 1
    CLUSTER_NETWORK: public
  when: redeploy | default(False) | bool
- name: 'Setup jumpbox'
  hosts:
    - "{{ CLUSTER_NAME }}{{ CLUSTER_NUMBER }}[-1]"
  gather_facts: True
  become: true
  vars:
    CLUSTER_NAME: jump
    CLUSTER_NUMBER: 1
    CLUSTER_NETWORK: public
  vars_files:
    - "{{ COMMON_DEPLOYMENT_DIR }}/common.yaml"
  roles:
    - role: common
      tags: common
    - role: filebeat
      when: FILEBEAT_LOGSTASH_HOST != ""
- include: ../playbooks/ami.yml
  when: redeploy | default(False) | bool
