---

# Requests library is required for the github status script.
- name: Install requests Python library
  pip: name=requests state=present

# Install Python 3.5. For now, do not set it as the default python
# version
- name: Install python 3.5
  apt:
    name: 'python3.5-dev'
    state: present
    update_cache: yes
