---
- name: Create additional configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ jenkins_analytics_configs_home }}/{{ item }}"
    owner: "{{ jenkins_analytics_configs_user }}"
    group: "{{ jenkins_analytics_configs_group }}"
    mode: "0640"
  with_items: "{{ jenkins_analytics_configs_templates }}"
- name: Remember to copy files to the appropriate S3 bucket
  debug:
    msg: "{{ item }} -> e.g. s://your-credential-bucket/{{ item }}"
  with_items:
    - edxapp_creds
    - edxanalytics_creds
