# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.network "forwarded_port", guest: 8010, host: 8010
  # config.vm.synced_folder '.ssh', '/home/vagrant/.ssh'
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 4096
  end
  # Enable X11 forwarding so we can interact with GUI applications
  if ENV['VAGRANT_X11']
    config.ssh.forward_x11 = true
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "../../../playbooks/vagrant-buildbot.yml"
    ansible.verbose = "vvvv"
  end
end
