---
- name: restart mysql
  service: 
    name: mysql 
    state: restarted

- name: restart tomcat6
  service: 
    name: tomcat6 
    state: restarted

- name: restart xvfb
  service: 
    name: xvfb 
    pattern: /etc/init.d/xvfb 
    state: restarted