---
tanguru_debian_pkgs:
  - openjdk-7-jre
  - unzip
  - libmysql-java
  - python-mysqldb
  - tomcat6 
  - libspring-instrument-java
  - xvfb
  - postfix
  - mailutils

tanaguru_download_link: "http://download.tanaguru.org/Tanaguru/tanaguru-3.1.0.i386.tar.gz"
# Go this link to find your desired ESR Firefox
# http://download-origin.cdn.mozilla.net/pub/firefox/releases/24.0esr/linux-x86_64/
# Default is en-US in our example
fixfox_esr_link: "http://download-origin.cdn.mozilla.net/pub/firefox/releases/24.0esr/linux-x86_64/en-US/firefox-24.0esr.tar.bz2"

tanaguru_parameters:
  - tanaguru_database: tgdatabase
    tanaguru_db_user: tguser
    tanaguru_db_password: "tgPassword"
    tanaguru_url: "http://localhost:8080/tanaguru/"
    tanaguru_admin_email: "admin@example.com"
    tg_admin_passwd: "tanaguru15"