---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role edx_vpc
# 
# Overview:
# This role creates an opinionated vpc for containing cluster of edx services.
# 
# It currently assumes that we will be multi-az, with a single NAT, and all
# traffic going over that NAT.  A public subnet, and both public and private
# route tables are created by default that can be used by new services in this
# vpc.  The public subnet should house ELBs and any newly created private subnets
# can use the existing private route table to be able to reach the internet from
# private machines.
# 
#
# Example play:
#
# ansible-playbook -c local -i localhost, edx_vpc.yml -e@/Users/feanil/src/edx-secure/cloud_migrations/vpcs/test.yml

# DO NOT use the subnet or route table sections of this command.
# They will delete any subnets or rts not defined here which is
# probably not what you want, since other services were added
# to the vpc whose subnets and rts are not enumerated here.
- name: create a vpc
  local_action:
    profile: "{{ vpc_aws_profile }}"
    module: "ec2_vpc_local"
    resource_tags: "{{ vpc_vpc_tags }}"
    cidr_block: "{{ vpc_vpc_cidr }}"
    region: "{{ vpc_aws_region }}"
    state: "{{ vpc_vpc_state }}"
    internet_gateway: "{{ vpc_vpc.internet_gateway.create }}"
    internet_gateway_tags: "{{ vpc_vpc.internet_gateway.tags }}"
    wait: yes
  register: created_vpc
  tags: vpc_only

- debug:
    var: created_vpc
