---
- name: Configure jenkins
  hosts: localhost
  sudo: True
  gather_facts: True
  vars:
    COMMON_BASE_DIR: ''
    jenkins_user: jenkins
    jenkins_group: jenkins
    jenkins_port: 80
    jenkins_server_name: jenkins.sandbox.class.stanford.edu
    user_info:
      - name: stvstnfrd
        type: admin
        github: True
  roles:
    - common
    - user
    - jenkins_master
