---
- name: create vpc
  ec2_vpc:
    state: present
    cidr_block: "{{ CIDR_VPC }}"
    resource_tags:
      Name: "{{ NAME_VPC }}"
    register: vpc

- name: create internet gateway
  ec2_vpc_igw:
    state: present
    vpc_id: vpc.id
    resource_tags:
      Name: "{{ NAME_INTERNET_GATEWAY }}"
    register: igw

- name: create subnet
  ec2_vpc_subnet:
    state: present
    vpc_id: vpc.id
    cidr: "{{ CIDR_SUBNET }}"
    az: "{{ AVAILABILITY_ZONE }}"
    resource_tags:
      Name: "{{ NAME_SUBNET }}"
    register: subnet

- name: create route table
  ec2_vpc_route_table:
    vpc_id: vpc.id
    region: "{{ REGION }}"
    tags:
      Name: "{{ NAME_ROUTE_TABLE }}"
    subnets:
      - "{{ subnet.id }}"
    routes:
      - dest: "{{ CIDR_PUBLIC }}"
        gateway_id: "{{ igw.id }}"

- name: create security group
  ec2_group:
    name: "{{ SECURITY_GROUP_NAME }}"
    description: "{{ SECURITY_GROUP_DESCRIPTION }}"
    vpc_id: "{{ vpc.id }}"
    region: "{{ REGION }}"
    rules:
      - proto: tcp
        from_port: "{{ PORT_LMS }}"
        to_port: "{{ PORT_LMS }}"
        cidr_ip: "{{ CIDR_PUBLIC }}"
      - proto: tcp
        from_port: "{{ PORT_CMS }}"
        to_port: "{{ PORT_CMS }}"
        cidr_ip: "{{ CIDR_PUBLIC }}"
      - proto: tcp
        from_port: "{{ PORT_SSH }}"
        to_port: "{{ PORT_SSH }}"
        cidr_ip: "{{ CIDR_PUBLIC }}"

- include: jenkins.yml tags=datadog
  when: ENABLE_JENKINS
