- hosts: localhost
  vars:
    secure_dir: '../../configuration-secure/ansible'
    playbook_dir: '../../configuration/playbooks'
    local_dir:  '../../configuration-secure/ansible/local'
  vars_files:
    - "{{ playbook_dir }}/roles/common/defaults/main.yml"
    - "{{ playbook_dir }}/roles/edxapp/defaults/main.yml"
    - "{{ secure_dir }}/vars/default/common.yaml"
    - "{{ secure_dir }}/vars/default/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/default/platform/embargo.yaml"
    - "{{ secure_dir }}/vars/default/platform/git-identity.yaml"
    - "{{ secure_dir }}/vars/default/platform/env.yaml"
    - "{{ secure_dir }}/vars/default/platform/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/users.yml"
    - "{{ secure_dir }}/vars/{{ env }}/shib.yml"
  tasks:
    - debug: var=playbook_dir
    - name: "create {{ item }} env file"
      template:
        src="{{ playbook_dir }}/roles/edxapp/templates/{{ item }}.env.json.j2"
        dest="/tmp/{{ env }}.{{ item }}.env.json"
      with_items:
        - 'lms'
        - 'cms'
    - name: "create {{ item }} auth file"
      template: >
        src="{{ playbook_dir }}/roles/edxapp/templates/{{ item }}.auth.json.j2"
        dest="/tmp/{{ env }}.{{ item }}.auth.json"
      with_items:
        - 'lms'
        - 'cms'
