---
- name: Setup XQueue
  # hosts: tag_environment_stage:&tag_group_xqueue
  hosts: ~tag_Name_{{ machine }}_{{ env }}
  sudo: True
  gather_facts: True
  vars:
    secure_dir: '../../configuration-secure/ansible'
    local_dir: '../../configuration-secure/ansible/local'
  vars_files:
    - "{{ secure_dir }}/vars/default/common.yaml"
    - "{{ secure_dir }}/vars/default/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/default/platform/embargo.yaml"
    - "{{ secure_dir }}/vars/default/platform/git-identity.yaml"
    - "{{ secure_dir }}/vars/default/platform/env.yaml"
    - "{{ secure_dir }}/vars/default/platform/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/defaults.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/env.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/platform/auth.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/users.yml"
    - "{{ secure_dir }}/vars/default/xqueue.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/xqueue.yml"
  roles:
    - role: nginx
      tags: nginx
    - role: xqueue
      tags: xqueue
