--
- name: Setup XQueue
  # hosts: tag_environment_stage:&tag_group_xqueue
  hosts: ~tag_Name_{{ machine }}_{{ env }}
  sudo: True
  gather_facts: True
  vars:
    secure_dir: '../../configuration-secure/ansible'
    local_dir: '../../configuration-secure/ansible/local'
    update_users: true
  vars_files:
    - "{{ secure_dir }}/vars/default/common.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/users.yml"
    - "{{ secure_dir }}/vars/default/xqueue.yaml"
    - "{{ secure_dir }}/vars/{{ env }}/xqueue.yml"
  roles:
    - role: nginx
      tags: nginx
      nginx_sites:
        - xqueue
        - basic-auth
    - role: xqueue
      tags: xqueue
