---

# Example sandbox configuration
# for single server community
# installs

- name: Configure instance(s)
  hosts: tag_Name_sandbox-instance-master
  sudo: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    edx_platform_version: 'master'
    # edx_platform_version: 'dcadams/merge_upstream_hotfix-2015-11-10_2'
    edxapp_theme_version: 'master'
    edxapp_use_custom_theme: true
    edxapp_theme_name: 'lagunita'
    edxapp_theme_source_repo: 'https://github.com/Stanford-Online/lagunita-theme.git'
    # SANDBOX_GITHUB_USERNAME: 'dcadams'
    # Set to false if deployed behind another proxy/load balancer.
    NGINX_SET_X_FORWARDED_HEADERS: True
    # user_info:
    #   - name: "{{ SANDBOX_GITHUB_USERNAME }}"
    #     github: true
    #     type: admin
  roles:
    - role: user
      tags: users
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      - forum
      - xqueue
      nginx_default_sites:
      - lms
    - mysql
    - edxlocal
    - mongo
    - { role: 'edxapp', celery_worker: True }
    - edxapp
    - analytics_api
    - insights
    - edx_notes_api
    - demo
    - oauth_client_setup
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - oraclejdk
    - elasticsearch
    - forum
    - { role: notifier, NOTIFIER_DIGEST_TASK_INTERVAL: "5" }
    - { role: "xqueue", update_users: True }
    - certs
    - edx_ansible
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
