- name: Deploy edX Prospectus Service
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'prospectus'
    PROSPECTUS_DATA_DIR: "/edx/var/prospectus"
  roles:
    - role: aws
      when: COMMON_ENABLE_AWS_ROLE
    - role: automated
      AUTOMATED_USERS: "{{ PROSPECTUS_AUTOMATED_USERS | default({}) }}"
    - role: nginx
      nginx_app_dir: "/etc/nginx"
      nginx_sites:
      - prospectus
      nginx_default_sites:
      - prospectus
      PROSPECTUS_NGINX_PORT: 8000
    - role: prospectus
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE
